### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by ikks** [Syndica/lmdb-zig#1]
Hi there, the project looks good. I would like to use it for https://github.com/ikks/tldrtranslate/ .  I also noticed that the db is created, but the keys are not stored in the database.

The objective is to cross compile from Debian to Windows and Macos.

**Comment by dnut** [comment]
> I also noticed that the db is created, but the keys are not stored in the database.

Thanks, yeah, I'm aware of that. There are also some other issues with the code in test.zig. I've been experimenting with lmdb in zig here if you want to see a better usage example: https://github.com/Syndica/sig/pull/373

Once that code is stabilized and merged, I'll add some improved helper functions and example code in this repository.

**Comment by ikks** [comment]
Thank you for addressing the license and all the hard work. I confirm for the case use of reading an already created db,  I can cross compile and use with no issues.
